# Generated by Django 5.2.4 on 2025-11-28 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosRadicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(max_length=10)),
                ('consecutivo', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.oficina')),
            ],
        ),
        migrations.CreateModel(
            name='RadicacionEnviados',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_radicacion', models.DateField()),
                ('medio_envio', models.CharField(max_length=50)),
                ('tipo_comunicacion', models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], max_length=10)),
                ('entidad', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=200)),
                ('num_rad_llegada', models.CharField(blank=True, max_length=20, null=True)),
                ('num_rad_interno', models.CharField(blank=True, max_length=20, null=True)),
                ('anexos', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('requiere_respuesta', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('N/A', 'N/A'), ('ANULADO', 'ANULADO')], max_length=10)),
                ('tiempo_respuesta', models.IntegerField(blank=True, null=True)),
                ('fecha_maxima_respuesta', models.DateField(blank=True, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('recibido', models.CharField(blank=True, max_length=10, null=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.oficina')),
                ('radicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviado_por', to='radicacion_app.responsable')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='RadicacionRecibidos',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_radicacion', models.DateField()),
                ('medio_ingreso', models.CharField(choices=[('Correo electronico', 'Correo electronico'), ('Fisico', 'Fisico'), ('Correo certificado', 'Correo certificado')], max_length=30)),
                ('tipo_comunicacion', models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], max_length=10)),
                ('num_rad_llegada', models.CharField(blank=True, max_length=20, null=True)),
                ('entidad', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=200)),
                ('anexos', models.IntegerField()),
                ('requiere_respuesta', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('TRAMITE INTERNO', 'TRAMITE INTERNO')], max_length=20)),
                ('tiempo_respuesta', models.IntegerField(blank=True, null=True)),
                ('fecha_maxima_respuesta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_respuesta', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Con Respuesta', 'Con Respuesta'), ('Sin Respuesta', 'Sin Respuesta')], max_length=20, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('medio_respuesta', models.CharField(blank=True, max_length=50, null=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.oficina')),
                ('radicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('respuesta_rad_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.radicacionenviados')),
                ('Responsable_por_responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_por_responder', to='radicacion_app.responsable')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.tipodocumento')),
            ],
        ),
    ]
