# Generated by Django 5.2.4 on 2025-11-28 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComunicacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='parametrosradicacion',
            name='contador',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosradicacion',
            name='tipo_comunicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.tipocomunicacion'),
            preserve_default=False,
        ),
    ]
