# Generated by Django 5.2.4 on 2025-12-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0002_tipocomunicacion_parametrosradicacion_contador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='radicacionrecibidos',
            old_name='Responsable_por_responder',
            new_name='responsable_por_responder',
        ),
    ]
