# Generated by Django 5.2.4 on 2025-12-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0003_entidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionrecibidos',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.entidad'),
        ),
    ]
