# Generated by Django 5.2.4 on 2025-12-04 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0004_alter_radicacionrecibidos_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionenviados',
            name='fecha_radicacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
