# Generated by Django 5.2.4 on 2025-12-04 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0005_alter_radicacionenviados_fecha_radicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionenviados',
            name='fecha_radicacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
