# Generated by Django 5.2.4 on 2025-12-04 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0006_alter_radicacionenviados_fecha_radicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametrosradicacion',
            options={'verbose_name_plural': 'Parámetros de Radicación'},
        ),
        migrations.RemoveField(
            model_name='parametrosradicacion',
            name='contador',
        ),
        migrations.AlterField(
            model_name='radicacionrecibidos',
            name='fecha_radicacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
