# Generated by Django 5.2.4 on 2025-12-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0008_alter_tipocomunicacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionrecibidos',
            name='respuesta_rad_interno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tipocomunicacion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='RadicacionEnviados',
        ),
    ]
