# Generated by Django 5.2.4 on 2025-12-05 02:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0009_alter_radicacionrecibidos_respuesta_rad_interno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadicacionEnviados',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_radicacion', models.DateField(default=datetime.date.today)),
                ('medio_envio', models.CharField(choices=[('Correo electronico', 'Correo electronico'), ('Fisico', 'Fisico'), ('Correo certificado', 'Correo certificado')], max_length=50)),
                ('tipo_comunicacion', models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], max_length=10)),
                ('asunto', models.CharField(max_length=200)),
                ('num_rad_llegada', models.CharField(blank=True, max_length=20, null=True)),
                ('num_rad_interno', models.CharField(blank=True, max_length=20, null=True)),
                ('anexos', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('requiere_respuesta', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('N/A', 'N/A'), ('ANULADO', 'ANULADO')], max_length=10)),
                ('tiempo_respuesta', models.IntegerField(blank=True, null=True)),
                ('fecha_maxima_respuesta', models.DateField(blank=True, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('recibido', models.CharField(blank=True, max_length=30, null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.entidad')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviado_por', to='radicacion_app.responsable')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.oficina')),
                ('radicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.tipodocumento')),
            ],
        ),
        migrations.AlterField(
            model_name='radicacionrecibidos',
            name='respuesta_rad_interno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.radicacionenviados'),
        ),
    ]
