# Generated by Django 5.2.4 on 2025-12-05 02:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0010_radicacionenviados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadicacionInternos',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_radicacion', models.DateField(default=datetime.date.today)),
                ('medio_ingreso', models.CharField(choices=[('Correo electronico', 'Correo electronico'), ('Fisico', 'Fisico'), ('Correo certificado', 'Correo certificado')], max_length=30)),
                ('tipo_comunicacion', models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], max_length=10)),
                ('num_rad_llegada', models.CharField(blank=True, max_length=20, null=True)),
                ('asunto', models.CharField(max_length=200)),
                ('anexos', models.IntegerField()),
                ('requiere_respuesta', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('TRAMITE INTERNO', 'TRAMITE INTERNO')], max_length=20)),
                ('tiempo_respuesta', models.IntegerField(blank=True, null=True)),
                ('fecha_maxima_respuesta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_respuesta', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Con Respuesta', 'Con Respuesta'), ('Sin Respuesta', 'Sin Respuesta')], max_length=20, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('medio_respuesta', models.CharField(blank=True, max_length=50, null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.entidad')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.oficina')),
                ('radicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('responsable_por_responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internos_por_responder', to='radicacion_app.responsable')),
                ('respuesta_rad_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.radicacionenviados')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.tipodocumento')),
            ],
        ),
    ]
