# Generated by Django 5.2.4 on 2025-12-27 00:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0011_radicacioninternos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadicadosRecibidosPqrsd',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_radicacion', models.DateField(default=datetime.date.today)),
                ('tipo_radicado', models.CharField(default='PQRSD', max_length=10)),
                ('unidad_negocio', models.CharField(choices=[('Buses', 'Buses'), ('Cable', 'Cable')], max_length=20)),
                ('fecha_recbido_user', models.DateField()),
                ('fecha_asignacion_traslado', models.DateField()),
                ('radicado_recibido', models.CharField(max_length=40)),
                ('canal_recepcion', models.CharField(max_length=50)),
                ('tipo_peticion', models.CharField(max_length=100)),
                ('nombre_remitente', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('fecha_evento', models.DateField()),
                ('hora_evento', models.TimeField()),
                ('lugar_evento', models.CharField(max_length=200)),
                ('serial_o_placa', models.CharField(max_length=20)),
                ('ruta', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('asignado_a', models.CharField()),
                ('vencimiento_interno', models.DateField()),
                ('vencimiento_por_ley', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('culpabilidad', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('No Aplica', 'No Aplica')], max_length=10)),
                ('operador', models.CharField(choices=[('Operador', 'Operador'), ('Operadora', 'Operadora'), ('No Aplica', 'No Aplica')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('radicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
