# Generated by Django 5.2.4 on 2025-12-28 18:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0012_radicadosrecibidospqrsd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('nombre_area', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CanalesRecepcion',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RutaVehiculo',
            fields=[
                ('ruta', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPeticion',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='radicadosrecibidospqrsd',
            old_name='fecha_recbido_user',
            new_name='fecha_recibido_usuario',
        ),
        migrations.AlterField(
            model_name='radicadosrecibidospqrsd',
            name='asignado_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.area'),
        ),
        migrations.AlterField(
            model_name='radicadosrecibidospqrsd',
            name='canal_recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.canalesrecepcion'),
        ),
        migrations.CreateModel(
            name='RadicadosEnviadosPqrsd',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_radicacion', models.DateField(default=datetime.date.today)),
                ('tipo_radicado', models.CharField(default='PQRSD', max_length=10)),
                ('asunto', models.CharField(max_length=200)),
                ('destinatario', models.CharField(max_length=200)),
                ('radicado_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.radicadosrecibidospqrsd')),
                ('radicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='radicadosrecibidospqrsd',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.rutavehiculo'),
        ),
        migrations.AlterField(
            model_name='radicadosrecibidospqrsd',
            name='asunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.tipologia'),
        ),
        migrations.AlterField(
            model_name='radicadosrecibidospqrsd',
            name='tipo_peticion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicacion_app.tipopeticion'),
        ),
    ]
