# Generated by Django 5.2.4 on 2025-12-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0013_area_canalesrecepcion_rutavehiculo_tipologia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicacionrecibidos',
            name='radicado_2025',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
