# Generated by Django 5.2.4 on 2025-12-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0014_radicacionrecibidos_radicado_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radicacionrecibidos',
            old_name='radicado_2025',
            new_name='num_radicado_2025',
        ),
    ]
