# Generated by Django 5.2.4 on 2025-12-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion_app', '0015_rename_radicado_2025_radicacionrecibidos_num_radicado_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionrecibidos',
            name='anexos',
            field=models.IntegerField(default=0),
        ),
    ]
