# Generated by Django 5.2.4 on 2025-09-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_app', '0002_alter_solicitudruta_fecha_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitudruta',
            name='fecha_solicitud',
            field=models.DateTimeField(default='2025-09-10 16:25:02'),
        ),
    ]
