# Generated by Django 5.2.4 on 2025-09-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_app', '0003_estadoruta_alter_solicitudruta_fecha_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudruta',
            old_name='estado',
            new_name='estado_bool',
        ),
        migrations.AlterField(
            model_name='solicitudruta',
            name='fecha_solicitud',
            field=models.DateTimeField(default='2025-09-10 16:41:59'),
        ),
    ]
