# Generated by Django 5.2.4 on 2025-09-10 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_app', '0004_rename_estado_solicitudruta_estado_bool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudruta',
            name='estado_bool',
        ),
        migrations.AddField(
            model_name='solicitudruta',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operaciones_app.estadoruta'),
        ),
        migrations.AlterField(
            model_name='solicitudruta',
            name='fecha_solicitud',
            field=models.DateTimeField(default='2025-09-10 16:43:06'),
        ),
    ]
