# Generated by Django 5.2.4 on 2025-09-11 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_app', '0005_remove_solicitudruta_estado_bool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelacionruta',
            name='solicitud',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operaciones_app.solicitudruta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudruta',
            name='fecha_solicitud',
            field=models.DateTimeField(default='2025-09-11 10:55:54'),
        ),
    ]
