# Generated by Django 5.2.4 on 2025-09-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_app', '0006_cancelacionruta_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudruta',
            name='fecha_solicitud',
            field=models.DateTimeField(default='2025-09-15 08:30:40'),
        ),
    ]
