# Generated by Django 5.2.4 on 2025-09-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_app', '0007_alter_solicitudruta_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudruta',
            name='fecha_solicitud',
            field=models.DateTimeField(default='2025-09-21 17:31:09'),
        ),
    ]
