# Generated by Django 5.2.4 on 2025-10-24 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento_app', '0010_alter_ordenalistamiento_fecha_creacion_orden'),
        ('operaciones_app', '0009_alter_solicitudruta_fecha_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etapa', models.CharField(max_length=50)),
                ('cant_items', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RutaFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitudruta',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ItemChequeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_item', models.CharField(max_length=100)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones_app.etapa')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento_app.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida', models.CharField(choices=[('P', 'Primera Salida'), ('S', 'Segunda Salida'), ('T', 'Tercera Salida')], max_length=1)),
                ('hora', models.TimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('firma', models.CharField(max_length=20)),
                ('nombre_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones_app.ordenflota')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_chequeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_item', models.CharField(choices=[('OK', 'OK'), ('P', 'Pendiente')], max_length=2)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones_app.etapa')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones_app.itemchequeo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones_app.ordenflota')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('1', 'Primer Turno'), ('2', 'Segundo Turno'), ('3', 'Tercer Turno')], max_length=1)),
                ('tabla', models.CharField(max_length=50)),
                ('instante', models.CharField(choices=[('IP', 'Inicio patio'), ('IO', 'Inicio Operacion'), ('FO', 'Fin Operacion'), ('EP', 'Entra Patio')], max_length=2)),
                ('km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=50)),
                ('apellido_operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apellido_operador', to=settings.AUTH_USER_MODEL)),
                ('codigo_operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nombre_operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_operador', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones_app.ordenflota')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones_app.rutaflota')),
            ],
        ),
    ]
