# Generated by Django 5.2.4 on 2025-11-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_app', '0010_etapa_rutaflota_alter_solicitudruta_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnoflota',
            name='apellido_operador',
        ),
        migrations.RemoveField(
            model_name='turnoflota',
            name='nombre_operador',
        ),
    ]
