# Generated by Django 5.2.4 on 2025-11-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_app', '0011_remove_turnoflota_apellido_operador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnoflota',
            name='nombre_operador',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
