# Generated by Django 5.2.4 on 2025-08-10 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cant_items', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('vehiculo_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento_app.etapa')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenAlistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion_orden', models.DateField(default='2025-08-10')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_alistamiento', models.IntegerField(blank=True, null=True)),
                ('novedades', models.TextField(blank=True, null=True)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento_app.estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento_app.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.IntegerField()),
                ('progreso', models.FloatField(default=0.0)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_inspeccion', models.IntegerField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento_app.estado')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento_app.etapa')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento_app.ordenalistamiento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento_app.estado')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento_app.etapa')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento_app.iteminspeccion')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento_app.ordenalistamiento')),
            ],
        ),
    ]
