# Generated by Django 5.2.4 on 2025-08-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenalistamiento',
            name='fecha_creacion_orden',
            field=models.DateField(default='2025-08-11'),
        ),
    ]
