# Generated by Django 5.2.4 on 2025-09-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento_app', '0005_alter_ordenalistamiento_fecha_creacion_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenalistamiento',
            name='fecha_creacion_orden',
            field=models.DateField(default='2025-09-10'),
        ),
    ]
