# Generated by Django 5.2.4 on 2025-09-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento_app', '0007_alter_ordenalistamiento_fecha_creacion_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenalistamiento',
            name='orden_trabajo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordenalistamiento',
            name='fecha_creacion_orden',
            field=models.DateField(default='2025-09-15'),
        ),
    ]
