# Generated by Django 5.2.4 on 2025-09-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento_app', '0008_ordenalistamiento_orden_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenalistamiento',
            name='fecha_creacion_orden',
            field=models.DateField(default='2025-09-21'),
        ),
    ]
