# Generated by Django 5.2.4 on 2025-11-11 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento_app', '0010_alter_ordenalistamiento_fecha_creacion_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenalistamiento',
            name='fecha_creacion_orden',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
